coding_task:
  description: >
    Write Python code to achieve this: {assignment}
  expected_output: >
    A text file that MUST HAVE the code that you wrote and executed in order to complete the given
    task, along with the output of the code.
  agent: coder
  output_file: output/code_and_output.txt

